### PR TITLE
New input types

### PR DESCRIPTION
**Pull request by fguimond**
Added support for the following input types:
* uint64
* unit32
* uint16
* int64
* int32
* int16

Also refactored unit tests to move argument and event validation tests in the `goplugin_test.go` instead of replicating them in `gohandler_test.go` and `gomutator_test.go`

### CODE REVIEW

**Comment by fguimond** [comment]
@nikkiki - As of now the library only supported boolean, uint64 and string arguments. The goal of this change is to add support for more types. Even though uint64 can include 16 and 32 bit values having explicit 16 and 32 bit types prevents the application from validating and casting values to the desired type. I followed the model laid out by `cobra` to implement this change. They do have explicit function calls for each type and since we're still using that library under the hood it made sense to do the same thing. I feel that using reflection might have been too error prone.

**Comment by nikkiki** [comment]
I guess I'm more confused as to why it is necessary within this library, if the logic is already present within Cobra. The existing plugins directly invoke Cobra, so I'm worried that wrapping the same logic within the plugins repo could make it more convoluted.

**Comment by fguimond** [comment]
@nikkixdev - Sorry about the delayed answer. The wrapper is used so we can use the environment variable value (if present) as a default value to pass into Cobra. Since Cobra has a one method per input type I simply used the same approach and added the environment variable logic on top of the Cobra call. This originally made sense since there was support for only 3 input types (int64, string, bool). However you bring up a good point that it's not optimal when adding more and more types. I took your suggestion of using reflection and added support for a lot more types.

**Comment by echlebek** [comment]
We can take a simpler approach to this.

**Pull request closed without merging**
